# Generated by Django 5.1 on 2024-10-01 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 1, 12, 47, 48, 253821, tzinfo=datetime.timezone.utc)),
        ),
    ]
